CeladonMansion2F_Script:
	jp EnableAutoTextBoxDrawing

CeladonMansion2F_TextPointers:
	def_text_pointers
	dw_const CeladonMansion2FMeetingRoomSignText, TEXT_CELADONMANSION2F_MEETING_ROOM_SIGN

CeladonMansion2FMeetingRoomSignText:
	text_far _CeladonMansion2FMeetingRoomSignText
	text_end
